### ISSUE TITLE
CheckInitializedApiUsage may be too eager

### ISSUE THREAD

**Issue by rwols** [packagecontrol/package_reviewer#12]
LaTeXTools seems to do some crazy stuff. [This file](https://github.com/SublimeText/LaTeXTools/blob/master/03_reset_phantoms.py) triggers CheckInitializedApiUsage but it looks like the author took care of it.
```python
if sublime.version() > '3118' and sublime_plugin.api_ready:
    for w in sublime.windows():
        for v in w.views():
            if v.score_selector(0, 'text.tex.latex') == 0:
                continue
            v.erase_phantoms('preview_math')
            v.erase_phantoms('preview_image')
            v.settings().clear_on_change('preview_math')
            v.settings().clear_on_change('preview_image')
    s = sublime.load_settings('LaTeXTools.sublime-settings')
    s.clear_on_change('preview_math')
    s.clear_on_change('preview_image')
```

**Comment by FichteFoll** [comment]
I think we can wipe this off as a simple false-positive that a human can dismiss. I don't see an easy way to exclude usage like this without analyzing if statements to check whether they access sublime_plugin.api_ready. There may be even more ways to do this.
