### ISSUE TITLE
CI failures in Python 3.6 due to changed syntax error message

### ISSUE THREAD

**Issue by Thom1729** [packagecontrol/package_reviewer#22]
The file `/tests/packages/ParseFailures/python2file.py` deliberately contains a Python 2-style `print` statement (with no parentheses). The `test_file_checkers` test looks for the error message. However, in Python 3.6, the error message was changed to be more specific. As a result, that test fails in Python 3.6.

**Comment by FichteFoll** [comment]
Hm, this is certainly annoying. We should make it our top priority to fix the test case as CI will continue to complain if we don't.
