### ISSUE TITLE
Remove Absolute Imports to Support Embedding

### ISSUE THREAD

**Issue by wbond** [packagecontrol/package_reviewer#27]
https://github.com/packagecontrol/st_package_reviewer/blob/ec640b203adaeefa3f365233a5ca40b88b7f7a3d/st_package_reviewer/check/file/ast/__init__.py#L4-L5 should really be relative imports.

**Comment by wbond** [comment]
Actually, this won't work due to the way the ast checker imports the code. I'll have to manually import my modified version as `st_package_reviewer` into `sys.modules`.

**Comment by FichteFoll** [comment]
They should be relative regardless, so I'll reopen this as a reminder.
